server:
  port: 8082

spring:
  application:
    name: payment-module
  profiles:
    active: docker

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true

  kafka:
    bootstrap-servers: kafka1:9092,kafka2:9094,kafka3:9096
    consumer:
      group-id: payment-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    org.apache.kafka: DEBUG
