version: '3.8'

services:
  kafka1:
    image: confluentinc/cp-kafka:7.5.1
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      CLUSTER_ID: 'EpwKlK0lR6qKZW0cGwZz8w'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka1:9092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9095,3@kafka3:9097'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
    volumes:
      - ./data/kafka1:/var/lib/kafka/data
    networks:
      - multi_network

  kafka2:
    image: confluentinc/cp-kafka:7.5.1
    container_name: kafka2
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 2
      CLUSTER_ID: 'EpwKlK0lR6qKZW0cGwZz8w'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_LISTENERS: 'PLAINTEXT://:9094,CONTROLLER://:9095'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka2:9094'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9095,3@kafka3:9097'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
    volumes:
      - ./data/kafka2:/var/lib/kafka/data
    networks:
      - multi_network

  kafka3:
    image: confluentinc/cp-kafka:7.5.1
    container_name: kafka3
    ports:
      - "9096:9096"
    environment:
      KAFKA_NODE_ID: 3
      CLUSTER_ID: 'EpwKlK0lR6qKZW0cGwZz8w'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_LISTENERS: 'PLAINTEXT://:9096,CONTROLLER://:9097'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka3:9096'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9095,3@kafka3:9097'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
    volumes:
      - ./data/kafka3:/var/lib/kafka/data
    networks:
      - multi_network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "9090:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:9092,kafka2:9094,kafka3:9096
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - multi_network


  order-module:
    build:
      context: ./order-module
    container_name: order-module
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KAFKA_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9094,kafka3:9096
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - multi_network

  payment-module:
    build:
      context: ./payment-module
    container_name: payment-module
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KAFKA_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9094,kafka3:9096
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - multi_network

  delivery-module:
    build:
      context: ./delivery-module
    container_name: delivery-module
    ports:
      - "8083:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KAFKA_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9094,kafka3:9096
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - multi_network

networks:
  multi_network:
    driver: bridge
